### ISSUE TITLE
Webpack warning when importing strftime

### ISSUE THREAD

**Issue by expaand** [benjaminoakes/moment-strftime#20]
Here is how I am using it in my code (of course, using babel..., etc.):
`import moment from 'moment-strftime';`

When webpack builds, it issues a warning on the js console:

```
client?440e:37 [WDS] Warnings while compiling.
client?440e:68 ../~/moment-strftime/lib/moment-strftime.js
Critical dependencies:
4:40-47 require function is used in a way in which dependencies cannot be statically extracted
 @ ../~/moment-strftime/lib/moment-strftime.js 4:40-47

```

**Comment by benjaminoakes** [comment]
This likely has something to do with [the `if` statement around the `require` call](https://github.com/benjaminoakes/moment-strftime/blob/master/lib/moment-strftime.js#L4).  If there's a solution that will allow working with Webpack, `npm`, and vanilla JS usage, I'd be interested in hearing more!

**Comment by j-f1** [comment]
@benjaminoakes See #21.

**Comment by benjaminoakes** [comment]
@j-f1 Merged, thanks!  I hadn't noticed the PR.
