### ISSUE TITLE
Wrong parsing method when first single character in sentence

### ISSUE THREAD

**Issue by Jeanquetil** [benjaminoakes/moment-strftime#25]
Related to #16 

The parsing method which escapes characters seems to not fully working. For instance, when the sentence starts with a single character that has to be escaped, actually it is not.

Example:
`a las 07:30` gives `am las 07:30`

It seems to come from the regex [here](https://github.com/benjaminoakes/moment-strftime/blob/master/lib/moment-strftime.js#L42) which is not matching a first single character and gives - for example - this: ![](https://cl.ly/1t080H3d3A3z/Image%202018-03-06%20at%2010.23.16%20AM.png)

**Comment by benjaminoakes** [comment]
Fixed in #28
