### ISSUE TITLE
link to compressed and development version broken

### ISSUE THREAD

**Issue by dhoss** [benjaminoakes/moment-strftime#5]
Can you fix the links to download the compressed and development versions?  The former returns an access denied error, probably due to the access token being expired, and the former just returns a 404.

Thanks!

**Comment by clemsos** [comment]
+1 here

**Comment by singpolyma** [comment]
+1

**Comment by benjaminoakes** [comment]
[Fixed](https://github.com/benjaminoakes/moment-strftime#browser).
